language: java

sudo: false

jdk:
  - oraclejdk13

install: true

script: mvn clean install coveralls:report

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.m2

notifications:
  email: false